require("IO.IO");
require("IO.Reader");
require("IO.Writer");

IO.ModAuth = {};
local LOCAL_MOD_KEY = "IntermodTesterA"; -- READ ME: Update this for your mod

---@enum ModAuthStage
IO.ModAuth.Stage = {
    Call = "Call";
    Response = "Response";
    Order = "Order";
};

local Stage = IO.ModAuth.Stage;

---Marks an order as a ModAuth message. It is the same in every mod so they recognise each other's messages, it is not the prefix a mod puts on its own payloads
local PAYLOAD_PREFIX = "ModAuth~";
local MAX_PAYLOAD_SIZE = 1024;

local KEY_PATTERN = "^[%w_%-]+$"; -- a mod key: only letters, digits, underscores and dashes, at least one character
local ID_PATTERN = "^%x%x%x%x%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x$";

---@class ModAuthMessage
---@field Stage ModAuthStage
---@field Target string # The mod the message is for
---@field Sender string # The mod that sent the message
---@field CallID GUID | nil # Generated by the calling mod, set on Call and Response
---@field Token GUID | nil # Generated by the responding mod, set on Response and Order
---@field Data table | nil # The order data, set on Order

---@class ModAuthQueuedOrder
---@field PlayerID PlayerID
---@field Data table

---@class ModAuthPendingCall
---@field Target string
---@field Queue ModAuthQueuedOrder[] # Orders to send once the target has responded

---@class ModAuthState
---@field Calls table<GUID, ModAuthPendingCall> # Calls this mod sent that are waiting for a response, by CallID
---@field Pending table<string, GUID> # The CallID of the call waiting for a response, by the target's key
---@field Sessions table<string, GUID> # The token to send with orders to each mod this mod has a session with, by the target's key
---@field Tokens table<GUID, string> # Tokens this mod issued and the mod each was issued to, by Token
---@field SelfToken GUID | nil # The token this mod puts on orders it sends to itself

-- annotations doesn't expose uuid, so wrap it
---@return GUID
local function NewID()
    ---@diagnostic disable-next-line: undefined-global
    return uuid();
end

---@param key any
---@return boolean
local function IsValidKey(key)
    return type(key) == "string" and string.match(key, KEY_PATTERN) ~= nil;
end

---@param id any
---@return boolean # true if id has the format of a GUID
local function IsValidID(id)
    return type(id) == "string" and string.match(id, ID_PATTERN) ~= nil;
end

---The state is held on the IO.ModAuth global, the server keeps it while it processes a turn. Reset clears it at the start of each turn.
---@type ModAuthState | nil
IO.ModAuth.State = nil;

---@return ModAuthState
local function NewState()
    return { Calls = {}, Pending = {}, Sessions = {}, Tokens = {} };
end

---@return ModAuthState
local function GetState()
    if (IO.ModAuth.State == nil) then IO.ModAuth.State = NewState(); end
    return IO.ModAuth.State;
end

---@param message ModAuthMessage
---@return string
local function Encode(message)
    return PAYLOAD_PREFIX .. IO.Writer.Write(message);
end

---Returns the table in a ModAuth payload, nil if it isn't one or can't be read. The table is not validated.
---@param payload string
---@return table | nil
local function Decode(payload)
    if (string.sub(payload, 1, #PAYLOAD_PREFIX) ~= PAYLOAD_PREFIX) then return nil; end
    if (#payload > MAX_PAYLOAD_SIZE) then return nil; end

    -- pcall isn't available, IO.Reader reports a bad payload by returning nil rather than throwing
    local message = IO.Reader.Read(string.sub(payload, #PAYLOAD_PREFIX + 1), "table");
    if (type(message) ~= "table") then return nil; end
    return message;
end

---@param playerID PlayerID
---@param description string
---@param message ModAuthMessage
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function SendMessage(playerID, description, message, addNewOrder)
    addNewOrder(WL.GameOrderCustom.Create(playerID, description, Encode(message), nil));
end

---Returns true if the message fits in a single order, larger ones aren't supported
---@param message ModAuthMessage
---@return boolean
local function FitsInOneOrder(message)
    return #Encode(message) <= MAX_PAYLOAD_SIZE;
end

---Reads a ModAuth message from an order, returns nil if it isn't a well formed ModAuth message
---@param order GameOrderCustom
---@return ModAuthMessage | nil
function IO.ModAuth.Parse(order)
    if (type(order.Payload) ~= "string") then return nil; end

    local message = Decode(order.Payload);
    if (message == nil) then return nil; end
    if (not IsValidKey(message.Target) or not IsValidKey(message.Sender)) then return nil; end

    if (message.Stage == Stage.Call) then
        if (not IsValidID(message.CallID)) then return nil; end
    elseif (message.Stage == Stage.Response) then
        if (not IsValidID(message.CallID) or not IsValidID(message.Token)) then return nil; end
    elseif (message.Stage == Stage.Order) then
        if (not IsValidID(message.Token) or type(message.Data) ~= "table") then return nil; end
    else
        return nil;
    end

    return message;
end

---@param targetMod string
---@param token GUID
---@param data table
---@return ModAuthMessage
local function BuildOrder(targetMod, token, data)
    return {
        Stage = Stage.Order,
        Target = targetMod,
        Sender = LOCAL_MOD_KEY,
        Token = token,
        Data = data };
end

---Sends data to targetMod as an authenticated order. The first send to a mod each turn opens a session with it (stages 1 and 2) and the order goes out once that completes, later sends reuse the session.
---@param targetMod string # The key of the mod being sent to
---@param playerID PlayerID # The player the order is issued as, can't be neutral
---@param data table # What to send targetMod as the authenticated order
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@return boolean sent # false if nothing was sent or queued because the mod keys are invalid or the data is too large
function IO.ModAuth.Send(targetMod, playerID, data, addNewOrder)
    if (not IsValidKey(LOCAL_MOD_KEY) or not IsValidKey(targetMod) or LOCAL_MOD_KEY == targetMod) then return false; end

    -- measured with a real GUID, so the size check holds whichever token ends up being used
    if (not FitsInOneOrder(BuildOrder(targetMod, NewID(), data))) then return false; end

    local state = GetState();

    local token = state.Sessions[targetMod];
    if (token ~= nil) then
        SendMessage(playerID, "ModAuth order", BuildOrder(targetMod, token, data), addNewOrder);
        return true;
    end

    local queued = { PlayerID = playerID, Data = data };

    -- a call to this mod is already waiting for its response, so join it instead of opening another session
    local pendingCall = state.Pending[targetMod] ~= nil and state.Calls[state.Pending[targetMod]] or nil;
    if (pendingCall ~= nil) then
        table.insert(pendingCall.Queue, queued);
        return true;
    end

    local callID = NewID();
    state.Calls[callID] = { Target = targetMod, Queue = { queued } };
    state.Pending[targetMod] = callID;

    SendMessage(playerID, "ModAuth call", {
        Stage = Stage.Call,
        Target = targetMod,
        Sender = LOCAL_MOD_KEY,
        CallID = callID },
        addNewOrder);
    return true;
end

---Sends data to this mod as an authenticated order, using this mod's own token for the turn instead of a session. ProcessOrder passes it to onAuthenticated with senderMod set to this mod's own key.
---@param playerID PlayerID # The player the order is issued as, can't be neutral
---@param data table # What to send this mod as the authenticated order
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@return boolean sent # false if nothing was sent because the mod key is invalid or the data is too large
function IO.ModAuth.SendSelf(playerID, data, addNewOrder)
    if (not IsValidKey(LOCAL_MOD_KEY)) then return false; end

    local message = BuildOrder(LOCAL_MOD_KEY, IO.ModAuth.GetSelfToken(), data);
    if (not FitsInOneOrder(message)) then return false; end

    SendMessage(playerID, "ModAuth order", message, addNewOrder);
    return true;
end

---Stage 2. Answers a call with a new token that only mods processing this turn's orders get to see
---@param message ModAuthMessage
---@param order GameOrderCustom
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function HandleCall(message, order, addNewOrder)
    local token = NewID();
    local state = GetState();
    state.Tokens[token] = message.Sender;

    SendMessage(order.PlayerID, "ModAuth response", { 
        Stage = Stage.Response,
        Target = message.Sender,
        Sender = LOCAL_MOD_KEY,
        CallID = message.CallID,
        Token = token },
        addNewOrder);
end

---Stage 3 (sending side). Opens the session with the token from the response and sends the orders queued while waiting
---@param message ModAuthMessage
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function HandleResponse(message, addNewOrder)
    local state = GetState();
    local call = state.Calls[message.CallID];
    -- only complete calls this mod made, to the mod it made them to
    if (call == nil or call.Target ~= message.Sender) then return; end

    state.Calls[message.CallID] = nil;
    state.Pending[call.Target] = nil;
    state.Sessions[call.Target] = message.Token;

    for _, queued in ipairs(call.Queue) do
        SendMessage(queued.PlayerID, "ModAuth order", BuildOrder(call.Target, message.Token, queued.Data), addNewOrder);
    end
end

---Stage 3 (receiving side). Passes the data on if the token was issued to the sender, or is this mod's own token for orders it sent itself. Tokens stay valid until Reset
---@param message ModAuthMessage
---@param order GameOrderCustom
---@param onAuthenticated? fun(senderMod: string, data: table, order: GameOrderCustom)
local function HandleOrder(message, order, onAuthenticated)
    if (message.Sender == LOCAL_MOD_KEY) then
        if (not IO.ModAuth.IsSelfToken(message.Token)) then return; end -- can't trust a token claiming to be this mod's own if it isn't
    elseif (GetState().Tokens[message.Token] ~= message.Sender) then
        return;
    end

    if (onAuthenticated ~= nil) then onAuthenticated(message.Sender, message.Data, order); end
end

---Call from Server_AdvanceTurn_Order. Handles any ModAuth order addressed to this mod.
---@param order GameOrder
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@param onAuthenticated? fun(senderMod: string, data: table, order: GameOrderCustom) # Called for each authenticated order, senderMod is this mod's own key for orders from SendSelf and otherwise only as trustworthy as the mod that made the call. Omit it if this mod only makes calls
---@return boolean handled # true if the order was a ModAuth message for this mod, so the caller can stop processing it
function IO.ModAuth.ProcessOrder(order, addNewOrder, onAuthenticated)
    if (order.proxyType ~= 'GameOrderCustom') then return false; end
    ---@cast order GameOrderCustom

    local message = IO.ModAuth.Parse(order);
    if (message == nil or message.Target ~= LOCAL_MOD_KEY) then return false; end

    if (message.Stage == Stage.Call) then
        HandleCall(message, order, addNewOrder);
    elseif (message.Stage == Stage.Response) then
        HandleResponse(message, addNewOrder);
    elseif (message.Stage == Stage.Order) then
        HandleOrder(message, order, onAuthenticated);
    end

    return true;
end

---Returns the token this mod puts on the orders it sends to itself, generated the first time it is asked for each turn.
---@return GUID
function IO.ModAuth.GetSelfToken()
    local state = GetState();
    if (state.SelfToken == nil) then state.SelfToken = NewID(); end
    return state.SelfToken;
end

---Returns true if token is this mod's own token for this turn, use it to check orders that claim to be from this mod.
---@param token any
---@return boolean
function IO.ModAuth.IsSelfToken(token)
    local selfToken = GetState().SelfToken;
    return selfToken ~= nil and token == selfToken;
end

---Call from Server_AdvanceTurn_Start on every turn.
function IO.ModAuth.Reset()
    IO.ModAuth.State = NewState();
end