require("IO.IO");
require("IO.Reader");
require("IO.Writer");

IO.ModAuth = {};
---@type ModKey
local LOCAL_MOD_KEY = "IntermodTesterB"; -- READ ME: Update this for your mod
local SKIP_HANDLED_AUTH_ORDERS = true; -- set to false while testing so the auth orders stay in the order list
local ENABLE_LOGGING = true; -- set to true to print what ModAuth is doing to the log

---@alias ModKey string # The key a mod identifies itself as when it authenticates with other mods

---@enum ModAuthStage
IO.ModAuth.Stage = {
    Call = "Call";
    Response = "Response";
    Order = "Order";
};

local Stage = IO.ModAuth.Stage;

local PAYLOAD_PREFIX = "ModAuth~"; --Marks an order as a ModAuth payload
local MAX_PAYLOAD_SIZE = 1024;

-- the message shown in the order list for each kind of ModAuth order
local CALL_MESSAGE = "ModAuth call";
local RESPONSE_MESSAGE = "ModAuth response";
local ORDER_MESSAGE = "ModAuth order";

local KEY_PATTERN = "^[%w_%-]+$"; -- only letters, digits, underscores and dashes, at least one character
local ID_PATTERN = "^%x%x%x%x%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x$"; -- GUID pattern

---@class ModAuthPayload
---@field Stage ModAuthStage
---@field TargetKey ModKey # The key of the mod the payload is for
---@field SenderKey ModKey # The key of the mod that sent the payload
---@field CallID GUID | nil # Generated by the calling mod, set on Call and Response
---@field Token GUID | nil # Generated by the responding mod, set on Response and Order
---@field Data table | nil # The order data, set on Order

---@class ModAuthQueuedOrder
---@field PlayerID PlayerID
---@field Data table

---@class ModAuthPendingCall
---@field CallID GUID # Sent with the call, the response has to bring it back
---@field QueuedOrders ModAuthQueuedOrder[] # Orders to send once the target has responded

---@class TurnModAuthState
---@field Calls table<ModKey, ModAuthPendingCall> # Calls this mod sent that are waiting for a response, by the target's key
---@field Sessions table<ModKey, GUID> # The token to send with orders to each mod this mod has a session with, by the target's key
---@field Tokens table<GUID, ModKey> # Tokens this mod issued and the mod each was issued to, by Token
---@field SelfToken GUID | nil # The token this mod puts on orders it sends to itself

---Prints the message to the log if ENABLE_LOGGING is set
---@param message string
local function Log(message)
    if (not ENABLE_LOGGING) then return; end
    print("[ModAuth " .. LOCAL_MOD_KEY .. "]: " .. tostring(message));
end

-- annotations doesn't expose uuid, so wrap it
---@return GUID
local function NewID()
    ---@diagnostic disable-next-line: undefined-global
    return uuid();
end

---@param key any
---@return boolean
local function IsValidKey(key)
    return type(key) == "string" and string.match(key, KEY_PATTERN) ~= nil;
end

---@param id any
---@return boolean # true if id has the format of a GUID
local function IsValidID(id)
    return type(id) == "string" and string.match(id, ID_PATTERN) ~= nil;
end

---The state is held on the IO.ModAuth global, the server keeps it while it processes a turn. Reset clears it at the start of each turn.
---@type TurnModAuthState | nil
IO.ModAuth.State = nil;

---@return TurnModAuthState
local function NewState()
    return { Calls = {}, Sessions = {}, Tokens = {} };
end

---@return TurnModAuthState
local function GetState()
    if (IO.ModAuth.State == nil) then IO.ModAuth.State = NewState(); end
    return IO.ModAuth.State;
end

---Call from Server_AdvanceTurn_Start on every turn.
function IO.ModAuth.Reset()
    IO.ModAuth.State = NewState();
    Log("New turn. Reset state.");
end

---Returns the token this mod puts on the orders it sends to itself, generated the first time it is asked for each turn.
---@return GUID
function IO.ModAuth.GetSelfToken()
    local state = GetState();
    if (state.SelfToken == nil) then state.SelfToken = NewID(); end
    return state.SelfToken;
end

---Returns true if the token is this mod's own token for this turn, use it to check orders that claim to be from this mod.
---@param token any
---@return boolean
function IO.ModAuth.IsSelfToken(token)
    local selfToken = GetState().SelfToken;
    return selfToken ~= nil and token == selfToken;
end

---@param payload ModAuthPayload
---@return string
local function Encode(payload)
    return PAYLOAD_PREFIX .. IO.Writer.Write(payload);
end

---Decodes the string in a custom order's payload into a table. Returns nil if the string isn't a ModAuth payload, is too long or can't be read. The table's contents are not validated.
---@param encodedPayload string # The payload of a custom order
---@return table | nil
local function Decode(encodedPayload)
    -- prefix and corruption check
    if (string.sub(encodedPayload, 1, #PAYLOAD_PREFIX) ~= PAYLOAD_PREFIX) then return nil; end
    if (#encodedPayload > MAX_PAYLOAD_SIZE) then 
        Log("Decoded payload too long: " .. #encodedPayload .. " > " .. MAX_PAYLOAD_SIZE);
        return nil;
    end

    local payload = IO.Reader.Read(string.sub(encodedPayload, #PAYLOAD_PREFIX + 1), "table");
    if (type(payload) ~= "table") then return nil; end
    return payload;
end

---@param playerID PlayerID
---@param message string # The message shown for the order in the order list
---@param payload ModAuthPayload # Encoded into the order's payload
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function AddNewAuthOrder(playerID, message, payload, addNewOrder)
    if(playerID == WL.PlayerID.Neutral) then
        Log("Error expected, sending ModAuth order as neutral player");
    end
    addNewOrder(WL.GameOrderCustom.Create(playerID, message, Encode(payload), nil));
end

---Returns true if the payload fits in a single order, larger ones aren't supported
---@param payload ModAuthPayload
---@return boolean
local function FitsInOneOrder(payload)
    local encodedPayload = Encode(payload);
    local fitsInOneOrder = #encodedPayload <= MAX_PAYLOAD_SIZE;
    if(not fitsInOneOrder) then Log("Payload too large for one order: " .. #encodedPayload .. " > " .. MAX_PAYLOAD_SIZE); end
    return fitsInOneOrder;
end

---@param targetModKey ModKey
---@param callID GUID
---@return ModAuthPayload
local function BuildCallPayload(targetModKey, callID)
    return {
        Stage = Stage.Call,
        TargetKey = targetModKey,
        SenderKey = LOCAL_MOD_KEY,
        CallID = callID };
end

---@param targetModKey ModKey
---@param callID GUID # The id of the call being answered
---@param token GUID
---@return ModAuthPayload
local function BuildResponsePayload(targetModKey, callID, token)
    return {
        Stage = Stage.Response,
        TargetKey = targetModKey,
        SenderKey = LOCAL_MOD_KEY,
        CallID = callID,
        Token = token };
end

---@param targetModKey ModKey
---@param token GUID
---@param data table
---@return ModAuthPayload
local function BuildOrderPayload(targetModKey, token, data)
    return {
        Stage = Stage.Order,
        TargetKey = targetModKey,
        SenderKey = LOCAL_MOD_KEY,
        Token = token,
        Data = data };
end

---Decodes and validates the ModAuth payload in a custom order.
---Returns nil if the order doesn't carry a payload or its fields are invalid (mod keys, stage, GUIDs or data)
---@param order GameOrderCustom
---@return ModAuthPayload | nil
function IO.ModAuth.Parse(order)
    if (type(order.Payload) ~= "string") then return nil; end

    local payload = Decode(order.Payload);
    if (payload == nil) then return nil; end
    if (not IsValidKey(payload.TargetKey) or not IsValidKey(payload.SenderKey)) then return nil; end

    -- check validity for 3 shapes of payload, stage dependent
    if (payload.Stage == Stage.Call) then
        if (not IsValidID(payload.CallID)) then return nil; end
    elseif (payload.Stage == Stage.Response) then
        if (not IsValidID(payload.CallID) or not IsValidID(payload.Token)) then return nil; end
    elseif (payload.Stage == Stage.Order) then
        if (not IsValidID(payload.Token) or type(payload.Data) ~= "table") then return nil; end
    else
        return nil;
    end

    return payload;
end

---Sends data to a target mod as an authenticated order. Reuses an existing auth session or starts a new one with a call
---@param targetModKey ModKey # The key of the mod being sent to
---@param playerID PlayerID # The player the order is issued as, can't be neutral
---@param data table # What to send the target mod as the authenticated order
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@return boolean sent # false if nothing was sent or queued
function IO.ModAuth.Send(targetModKey, playerID, data, addNewOrder)
    Log(targetModKey .. " requested to send an authenticated order with data " .. IO.Writer.Write(data));

    -- check mod identifying keys are valid
    if (not IsValidKey(LOCAL_MOD_KEY) or not IsValidKey(targetModKey) or LOCAL_MOD_KEY == targetModKey) then return false; end

    -- checks if the order will fit in a single order, larger ones aren't supported currently. TODO: handle splitting into multiple orders and reassembling on the other side
    if (not FitsInOneOrder(BuildOrderPayload(targetModKey, NewID(), data))) then return false; end

    local state = GetState();

    local token = state.Sessions[targetModKey];
    if (token ~= nil) then
        Log("Existing session with " .. targetModKey .. ", sending order with token " .. token);
        AddNewAuthOrder(playerID, ORDER_MESSAGE, BuildOrderPayload(targetModKey, token, data), addNewOrder);
        return true;
    end

    -- multiple orders may be sent to the same mod before it responds, queue them up and send once we can send them authenticated
    local queued = { PlayerID = playerID, Data = data };

    -- if a call to this mod is already waiting for its response, join the queue for orders
    local pendingCall = state.Calls[targetModKey];
    if (pendingCall ~= nil) then
        table.insert(pendingCall.QueuedOrders, queued);
        return true;
    end

    local callID = NewID();
    state.Calls[targetModKey] = { CallID = callID, QueuedOrders = { queued } };

    local callPayload = BuildCallPayload(targetModKey, callID);
    Log("No session with " .. targetModKey .. ", sending call with payload " .. IO.Writer.Write(callPayload) .. " and queuing order");
    AddNewAuthOrder(playerID, CALL_MESSAGE, callPayload, addNewOrder);
    return true;
end

---Sends data to this mod as an authenticated order, using this mod's own token for the turn instead of a session
---@param playerID PlayerID # The player the order is issued as, can't be neutral
---@param data table # What to send this mod as the authenticated order
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@return boolean sent # false if nothing was sent because the mod key is invalid or the data is too large
function IO.ModAuth.SendSelf(playerID, data, addNewOrder)
    if (not IsValidKey(LOCAL_MOD_KEY)) then return false; end

    local payload = BuildOrderPayload(LOCAL_MOD_KEY, IO.ModAuth.GetSelfToken(), data);
    if (not FitsInOneOrder(payload)) then return false; end

    Log("Sending self-authenticated order to " .. LOCAL_MOD_KEY .. " with payload " .. IO.Writer.Write(payload));
    AddNewAuthOrder(playerID, ORDER_MESSAGE, payload, addNewOrder);
    return true;
end

---Handles a call (stage 1). Answers it with a response carrying a new token for a single-turn session
---@param payload ModAuthPayload
---@param order GameOrderCustom
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function HandleCall(payload, order, addNewOrder)
    Log("Handling call " .. payload.CallID .. " from " .. payload.SenderKey);

    local token = NewID();
    local state = GetState();
    state.Tokens[token] = payload.SenderKey;

    local responsePayload = BuildResponsePayload(payload.SenderKey, payload.CallID, token);
    Log("Sending response with payload " .. IO.Writer.Write(responsePayload));
    AddNewAuthOrder(order.PlayerID, RESPONSE_MESSAGE, responsePayload, addNewOrder);
end

---Handles a response (stage 2). Opens the single-turn session with its token and sends the orders queued while waiting for it
---@param payload ModAuthPayload
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
local function HandleResponse(payload, addNewOrder)
    Log("Handling response " .. payload.CallID .. " from " .. payload.SenderKey .. " with token " .. payload.Token);

    local state = GetState();

    -- validate we are tracking the payload call id
    local call = state.Calls[payload.SenderKey];
    if (call == nil or call.CallID ~= payload.CallID) then
        Log("Ignoring response from " .. payload.SenderKey .. ", call not found");
        return;
    end

    -- untrack the call and populate the session
    state.Calls[payload.SenderKey] = nil;
    state.Sessions[payload.SenderKey] = payload.Token;

    Log("Session opened with " .. payload.SenderKey .. ", sending " .. #call.QueuedOrders .. " queued order(s)");
    for _, queued in ipairs(call.QueuedOrders) do
        Log("Sending queued order to " .. payload.SenderKey .. ", using token " .. payload.Token .. " with data " .. IO.Writer.Write(queued.Data));
        AddNewAuthOrder(queued.PlayerID, ORDER_MESSAGE, BuildOrderPayload(payload.SenderKey, payload.Token, queued.Data), addNewOrder);
    end
end

---Handles an authenticated order (stage 3). Validates the session then carries out the underlying requested order by calling onAuthenticated
---@param payload ModAuthPayload
---@param order GameOrderCustom
---@param onAuthenticated? fun(senderModKey: ModKey, data: table, order: GameOrderCustom)
local function HandleOrder(payload, order, onAuthenticated)
    if (payload.SenderKey == LOCAL_MOD_KEY) then
        if (not IO.ModAuth.IsSelfToken(payload.Token)) then -- can't trust a token claiming to be this mod's own if it isn't
            Log("Rejected order with self-claim. Invalid token " .. tostring(payload.Token));
            return;
        end
    elseif (GetState().Tokens[payload.Token] ~= payload.SenderKey) then
        Log("Rejected order from " .. payload.SenderKey .. ", invalid token " .. tostring(payload.Token));
        return;
    end

    Log("Authenticated order from " .. payload.SenderKey);
    -- finally, we can carry out the underlying order that the mod wanted sent
    if (onAuthenticated ~= nil) then onAuthenticated(payload.SenderKey, payload.Data, order); end
end

---Call from Server_AdvanceTurn_Order. Handles any ModAuth order addressed to this mod, then skip and suppresses it
---@param order GameOrder
---@param addNewOrder fun(order: GameOrder, skipIfOriginalSkipped?: boolean)
---@param skipThisOrder fun(modOrderControl: EnumModOrderControl) # The skip function the order hook was given
---@param onAuthenticated? fun(senderModKey: ModKey, data: table, order: GameOrderCustom) # Called for each authenticated order sent to this mod. Omit if this mod only makes calls
---@return boolean handled # true if the order was a ModAuth order for this mod, so the caller can stop processing it
function IO.ModAuth.ProcessOrder(order, addNewOrder, skipThisOrder, onAuthenticated)
    if (order.proxyType ~= 'GameOrderCustom') then return false; end
    ---@cast order GameOrderCustom

    local payload = IO.ModAuth.Parse(order);
    if (payload == nil or payload.TargetKey ~= LOCAL_MOD_KEY) then return false; end

    if (payload.Stage == Stage.Call) then
        HandleCall(payload, order, addNewOrder);
    elseif (payload.Stage == Stage.Response) then
        HandleResponse(payload, addNewOrder);
    elseif (payload.Stage == Stage.Order) then
        HandleOrder(payload, order, onAuthenticated);
    end

    if (SKIP_HANDLED_AUTH_ORDERS) then skipThisOrder(WL.ModOrderControl.SkipAndSupressSkippedMessage); end
    return true;
end